pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { 
          image 'maven:3.8.1-adoptopenjdk-11'
          args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { 
          image 'node:16-alpine'
          args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
